E-lections/E-lections/Models/Glasac.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_lections.Models
{
    public class Glasac : Osoba
    {
        public void Glasaj(int idKandidata)
        {
            throw new NotImplementedException();
        }

        public void KandidujSe()
        {
            throw new NotImplementedException();
        }
    }
}

E-lections/E-lections/Models/Stranka.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_lections.Models
{
    public class Stranka
    {
        public int ID { get; set; }
        [Display(Name = "Naziv stranke")]
        public string Naziv { get; set; }

        //veze
        public virtual ICollection<Osoba> UpisiUStranku { get; set; } 


        public void DodajClana(Osoba o)
        {
            //TODO
        }

        public void IzbaciClana(int id)
        {
            //TODO
        }
    }
}

E-lections/E-lections/Controllers/GlasacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using E_lections.Models;
using Microsoft.EntityFrameworkCore;

namespace E_lections.Controllers
{
    public class GlasacController : Controller
    {
        private ELectionsDbContext _context;
        private static int? currentIzbor;
        private static int? listicId;

        public GlasacController(ELectionsDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View("Index", HomeController.currentlyLogged);
        }

        public IActionResult Izbori()
        {
            return View(_context.Izbor.Include(i => i.GlasackiListici).Include(i => i.Statistika).Where(i => i.Status == StatusIzbora.Aktivan && i.KantonOgranicenje.Equals(HomeController.currentlyLogged.Kanton)).ToList());
        }

        public IActionResult Stranka()
        {
            return View(_context.Stranka.ToList());
        }

        public IActionResult NapustiStranku()
        {
            if(HomeController.currentlyLogged.StrankaId == null)
                ViewBag.Message = "Niste član niti jedne stranke!";
            else
            {
                ViewBag.Message = "Napustili ste stranku!";
                var stranka = _context.Stranka.Include(c => c.UpisiUStranku).FirstOrDefault(s => s.ID == HomeController.currentlyLogged.StrankaId);
                var osoba = stranka.UpisiUStranku.First(o => o.StrankaId == HomeController.currentlyLogged.StrankaId);
                stranka.UpisiUStranku.Remove(osoba);
                _context.SaveChanges();
                HomeController.currentlyLogged.StrankaId = null;
                HomeController.currentlyLogged.Stranka = null;
            }
            return View("Index");
        }

        public IActionResult UclaniSe(int id)
        {
            if(HomeController.currentlyLogged.StrankaId != null)
            {
                ViewBag.Message = "Već ste član stranke!";
                return View("Stranka", _context.Stranka.ToList());
            }
            var stranka = _context.Stranka.Include(c => c.UpisiUStranku).FirstOrDefault(s => s.ID == id);
            var osoba = _context.Osoba.Where(o => o.ID == HomeController.currentlyLogged.ID).FirstOrDefault();
            stranka.UpisiUStranku.Add(osoba);
            _context.SaveChanges();
            return View("Index");
        }

        public IActionResult Detalji(int? id)
        {
            currentIzbor = id;
            return View(_context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == id).ToList());
        }

        public IActionResult Rezultati(int? id)
        {
            var glasackiListic = _context.GlasackiListic.Include(g => g.Izbor).Include(g => g.Kandidati).Where(g => g.ID == id).FirstOrDefault();
            return View(glasackiListic.Kandidati);
        }


        public IActionResult DetaljiKandidata(int? id)
        {
            listicId = id;
            return View(_context.Kandidat.Where(k => k.GlasackiListicId == id).ToList());
        }

        public IActionResult LogOut()
        {
            HomeController.currentlyLogged = null;
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Prijava()
        {
            var glasac = _context.Glasac.FirstOrDefault(i => i.ID == HomeController.currentlyLogged.ID);
            Kandidat k = getKandidat(glasac);
            _context.Kandidat.Add(k);
            _context.Glasac.Remove(glasac);
            _context.SaveChanges();
            HomeController.currentlyLogged = k;
            return RedirectToAction("Change", "Home");
        }

        public IActionResult Glasaj(int? id)
        {
            var glasac = _context.Osoba.Include(g => g.HistorijaGlasanja).FirstOrDefault(g => g.ID == HomeController.currentlyLogged.ID);
            var opcije = _context.GlasackiListic.Include(g => g.Kandidati).Include(g => g.Izbor).Where(g => g.ID == id).FirstOrDefault();
            if (DateTime.Now < opcije.Izbor.Pocetak)
            {
                ViewBag.Glasao = "Izbori još nisu počeli!";
                return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());

            }
            if (DateTime.Now > opcije.Izbor.Pocetak.AddHours(12))
            {
                ViewBag.Glasao = "Izbori su završeni!";
                return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
            }
            if (glasac.HistorijaGlasanja == null)
            {
                glasac.HistorijaGlasanja = new HistorijaGlasanja();
                glasac.HistorijaGlasanja.DodajGlas((int)id);
            }
            else
            {
                foreach(var listic in glasac.HistorijaGlasanja.DajGlasove())
                {
                    if(listic == id)
                    {
                        ViewBag.Glasao = "Već ste glasali na ovom glasačkom listiću";
                        return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
                    }
                }
                glasac.HistorijaGlasanja.DodajGlas((int)id);
            }
            _context.SaveChanges();
            return View(opcije);
        }

        [HttpPost]
        public IActionResult Glasaj(string[] glasovi)
        {

            var glas = _context.GlasackiListic.Where(i => i.IzborId == currentIzbor).FirstOrDefault();
            List<int> lista = new List<int>();
            foreach(string s in glasovi)
            {
                lista.Add(Int32.Parse(s));
            }
            foreach (int id in lista)
            {
                if (glasovi.Length <= glas.MaxOdabir)
                {
                    var osoba = _context.Kandidat.FirstOrDefault(k => k.ID == id);
                    osoba.brojGlasova++;
                }
            }
            var izbor = _context.Izbor.Include(i => i.Statistika).Where(i => i.ID == currentIzbor).FirstOrDefault();
            if (izbor.Statistika == null) izbor.Statistika = new Statistika();
            if (HomeController.currentlyLogged.Spol == Spol.Muski) izbor.Statistika.GlasoviMusko++;
            else izbor.Statistika.GlasoviZensko++;
            if (glasovi.Length == 0 || glasovi.Length > glas.MaxOdabir) izbor.Statistika.GlasoviNevalidni++;
            else
            {
                izbor.Statistika.GlasoviValidni++;
            }
            _context.SaveChanges();
            ViewBag.PorukaGlasanje = "Hvala što ste glasali!";
            return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
        }

        public IActionResult ProfilKandidata(int? id)
        {

            var kandidat = _context.Kandidat.Include(k => k.Profil).Where(k => k.ID == id).FirstOrDefault();
            if(kandidat.Profil == null)
            {
                ViewBag.Message = "Ovaj kandidat nema profil kojeg možete pogledati";
                return View("DetaljiKandidata", _context.Kandidat.Where(k => k.GlasackiListicId == listicId).ToList());
            }
            return View(kandidat.Profil);
        }

        public IActionResult Izvjestaj(int id)
        {
            var izbor = _context.Izbor.Include(i => i.Statistika).Where(i => i.ID == id).FirstOrDefault();
            return View(izbor.Statistika);
        }

        private Kandidat getKandidat(Osoba osoba)
        {
            Kandidat k = new Kandidat();
            k.Ime = osoba.Ime;
            k.Prezime = osoba.Prezime;
            k.DatumRodjenja = osoba.DatumRodjenja;
            k.JMBG = osoba.JMBG;
            k.BrojLicneKarte = osoba.BrojLicneKarte;
            //k.BirackoMjestoID = osoba.BirackoMjestoID;
            k.StrankaId = osoba.StrankaId;
            k.Spol = osoba.Spol;
            k.Ulica = osoba.Ulica;
            k.Kanton = osoba.Kanton;
            k.Lozinka = osoba.Lozinka;
            k.EMail = osoba.EMail;
            k.isSelected = false;
            return k;
        }

    }
}

E-lections/E-lections/Views/Glasac/Detalji.cshtml
@model IEnumerable<E_lections.Models.GlasackiListic>

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}


<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                Broj kandidata
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @item.Kandidati.Count()
            <td>
                <a asp-action="DetaljiKandidata" asp-route-id="@item.ID">Detalji</a>
            </td>
            <td>
                <a asp-action="Glasaj" asp-controller="Glasac" asp-area="" asp-route-id="@item.ID">Glasaj</a>
            </td>
            <td>
                <a asp-action="Rezultati" asp-controller="Glasac" asp-area="" asp-route-id="@item.ID">Rezultati</a>
            </td>
        </tr>
        }
    </tbody>
</table>

<div align="center">
    @if (ViewBag.Message != null)
    {
        <h2>@ViewBag.Message</h2>
    }
    @if (ViewBag.PorukaGlasanje != null)
    {
        <h2>
            @ViewBag.PorukaGlasanje
        </h2>
    }
    @if (ViewBag.Glasao != null)
    {
        <h2>@ViewBag.Glasao</h2>
    }
</div>

E-lections/E-lections/Views/Glasac/DetaljiKandidata.cshtml
@model IEnumerable<E_lections.Models.Kandidat>

@{
    ViewData["Title"] = "DetaljiKandidata";
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}

<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kanton)
            </th>
            <th>
               Stranka
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumRodjenja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kanton)
            </td>
            @if (item.StrankaId != null)
             {
               <td>@Html.DisplayFor(modelItem => item.Stranka.Naziv)</td>
             }
             else
             {
               <td>Nezavisni kandidat</td>
             }
            <td>
                <a asp-action="ProfilKandidata" asp-route-id="@item.ID">Pogledaj profil</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div align="center">
    @if (ViewBag.Message != null)
    {
        <h2>
            @ViewBag.Message
        </h2>
    }
</div>

E-lections/E-lections/Views/Glasac/Glasaj.cshtml
@model E_lections.Models.GlasackiListic

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}

<div class="signin">
    @using (Html.BeginForm("Glasaj", "Glasac"))
    {
        <form method="post">
            @foreach (var item in Model.Kandidati)
            {
            <div class="whiteLettersAndCenter">
                @item.Ime @item.Prezime
                <input type="checkbox" name="glasovi" value="@item.ID" />
                <br />
            </div>
            }
            <input type="submit" class="btn" value="Glasaj" />
        </form>
    }
</div>

E-lections/E-lections/Views/Glasac/Index.cshtml
@model E_lections.Models.Glasac

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}



<body>
    <div class="signin">
        <div>
            <ul class="list">
                <li>
                    <a class="link" asp-action="Stranka" asp-controller="Glasac" asp-area="">Učlani se u stranku</a>
                </li>
                <li>
                    <a class="link" asp-action="NapustiStranku" asp-controller="Glasac" asp-area="">Napusti stranku</a>
                </li>
            </ul>
        </div>
    </div>
    <hr />
    <div align="center">
        @if (ViewBag.Message != null)
        {
            <h2>
                @ViewBag.Message
            </h2>
        }
    </div>
</body>

E-lections/E-lections/Views/Glasac/Izbori.cshtml
@model IEnumerable<E_lections.Models.Izbor>

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}

<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pocetak)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KantonOgranicenje)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pocetak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KantonOgranicenje)
            </td>
            <td>
                <a asp-action="Detalji" asp-route-id="@item.ID">Detaljno</a> |
                @if(item.Statistika != null && item.Statistika.Visible == true)
                {
                    <a asp-action="Izvjestaj" asp-route-id="@item.ID">Izvještaj</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>

E-lections/E-lections/Views/Glasac/Izvjestaj.cshtml
@model E_lections.Models.Statistika

@{
    ViewData["Title"] = "Izvjestaj";
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}

<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviMusko)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviZensko)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviValidni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviNevalidni)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviMusko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviZensko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviValidni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviNevalidni)
            </td>
        </tr>
    </tbody>
</table>

E-lections/E-lections/Views/Glasac/ProfilKandidata.cshtml
@model E_lections.Models.Profil

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}


<div class="signin">
    <textarea  rows="10" cols="33" readonly="readonly" >
            @Model.Opis
    </textarea>
</div>

E-lections/E-lections/Views/Glasac/Rezultati.cshtml
@model IEnumerable<E_lections.Models.Kandidat>

@{
    ViewData["Title"] = "Rezultati";
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}


<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brojGlasova)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumRodjenja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brojGlasova)
            </td>
        </tr>
}
    </tbody>
</table>

E-lections/E-lections/Views/Glasac/Stranka.cshtml
@model IEnumerable<E_lections.Models.Stranka>

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}

<body>
    <table class="content-table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        <a asp-action="UclaniSe" asp-route-id="@item.ID">Učlani se</a> |
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <hr />
    <div align="center">
        @if (ViewBag.Message != null)
        {
            <h2>
                @ViewBag.Message
            </h2>
        }
    </div>
</body>

E-lections/E-lections/Views/Glasac/View.cshtml
@model E_lections.Models.Glasac

@{
    Layout = "~/Views/Shared/_LayoutGlasac.cshtml";
}


<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumRodjenja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumRodjenja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrojLicneKarte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrojLicneKarte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JMBG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JMBG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spol)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lozinka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lozinka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ulica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ulica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kanton)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kanton)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stranka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stranka.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirackoMjesto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirackoMjesto.ID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>