E-lections/E-lections/Models/Kandidat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_lections.Models
{
    public class Kandidat : KandidatDekorater, IUcesnik
    {
        [Display(Name = "Broj glasova")]
        public int brojGlasova { get; set; } = 0;

        //veze sa ostalim tabelama, 1:1 veza sa Profil,  1:m veza sa glasackim listicem, m:n veza sa BirackoMjesto
        public int? ProfilId { get; set; }
        public virtual Profil Profil { get; set; }

        public int? GlasackiListicId { get; set; }
        public virtual GlasackiListic GlasackiListic { get; set; }

        public bool isSelected { get; set; } = false;

        
        public void DodajGlas()
        {
            throw new NotImplementedException();
        }

        public void PrijaviIzbore(int idIzbora, int idListica)
        {
            throw new NotImplementedException();
        }

        public void Update()
        {
            throw new NotImplementedException();
        }
    }
}

E-lections/E-lections/Models/Profil.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_lections.Models
{
    public class Profil
    {

        public int ID { get; set; }
        [Display(Name = "Opis profila")]
        public string Opis { get; set; }
        public string PutanjaSlike { get; set; }

        public virtual Kandidat Kandidat { get; set; }

    }
}

E-lections/E-lections/Models/Stranka.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_lections.Models
{
    public class Stranka
    {
        public int ID { get; set; }
        [Display(Name = "Naziv stranke")]
        public string Naziv { get; set; }

        //veze
        public virtual ICollection<Osoba> UpisiUStranku { get; set; } 


        public void DodajClana(Osoba o)
        {
            //TODO
        }

        public void IzbaciClana(int id)
        {
            //TODO
        }
    }
}

E-lections/E-lections/Controllers/KandidatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using E_lections.Models;

namespace E_lections.Controllers
{
    public class KandidatController : Controller
    {

        private ELectionsDbContext _context;
        private static int? currentIzbor;
        private static int? listicId;

        public KandidatController(ELectionsDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View("Index", HomeController.currentlyLogged);
        }

        public IActionResult Izbori()
        {
            return View(_context.Izbor.Include(i => i.GlasackiListici).Include(i => i.Statistika).Where(i => i.Status == StatusIzbora.Aktivan && i.KantonOgranicenje.Equals(HomeController.currentlyLogged.Kanton)).ToList());
        }

        public IActionResult Stranka()
        {
            return View(_context.Stranka.ToList());
        }

        public IActionResult NapustiStranku()
        {
            if (HomeController.currentlyLogged.StrankaId == null)
                ViewBag.Message = "Niste član niti jedne stranke!";
            else
            {
                ViewBag.Message = "Napustili ste stranku!";
                var stranka = _context.Stranka.Include(c => c.UpisiUStranku).FirstOrDefault(s => s.ID == HomeController.currentlyLogged.StrankaId);
                var osoba = stranka.UpisiUStranku.First(o => o.StrankaId == HomeController.currentlyLogged.StrankaId);
                stranka.UpisiUStranku.Remove(osoba);
                _context.SaveChanges();
                HomeController.currentlyLogged.StrankaId = null;
                HomeController.currentlyLogged.Stranka = null;
            }
            return View("Index");
        }

        public IActionResult UclaniSe(int id)
        {
            if (HomeController.currentlyLogged.StrankaId != null)
            {
                ViewBag.Message = "Već ste član stranke!";
                return View("Stranka", _context.Stranka.ToList());
            }
            var stranka = _context.Stranka.Include(c => c.UpisiUStranku).FirstOrDefault(s => s.ID == id);
            var osoba = _context.Kandidat.Where(k => k.ID == HomeController.currentlyLogged.ID).FirstOrDefault();
            stranka.UpisiUStranku.Add(osoba);
            _context.SaveChanges();
            return View("Index");
        }

        public IActionResult Detalji(int? id)
        {
            ViewBag.Listic = _context.Kandidat.FirstOrDefault(k => k.ID == HomeController.currentlyLogged.ID).GlasackiListicId;
            currentIzbor = id;
            return View(_context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == id).ToList());
        }

        public IActionResult Rezultati(int ?id)
        {
            var glasackiListic = _context.GlasackiListic.Include(g => g.Izbor).Include(g => g.Kandidati).Where(g => g.ID == id).FirstOrDefault();
            return View(glasackiListic.Kandidati);
        }

        public IActionResult DetaljiKandidata(int? id)
        {
            listicId = id;
            return View(_context.Kandidat.Where(k => k.GlasackiListicId == id).ToList());
        }

        public IActionResult Prijava(int? id)
        {
            Kandidat k = _context.Kandidat.Include(ka => ka.GlasackiListic).Where(ka => ka.ID == HomeController.currentlyLogged.ID).FirstOrDefault();
            if(k.GlasackiListic != null)
            {
                ViewBag.Message = "Već ste prijavljeni na izbore!";
                return View("Detalji", _context.GlasackiListic.Include(g => g.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
            }
            var glasackiListic = _context.GlasackiListic.Include(g => g.Kandidati).Include(g => g.Izbor).FirstOrDefault(g => g.ID == id);
            var izboriPoc = glasackiListic.Izbor.Pocetak;
            if(DateTime.Now > izboriPoc)
            {
                ViewBag.Message = "Prijave su završene!";
                return View("Detalji", _context.GlasackiListic.Include(g => g.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
            }
            glasackiListic.Kandidati.Add(k);
            _context.SaveChanges();
            ViewBag.Message = "Uspješno ste se prijavili na izbore!";
            return View("Detalji", _context.GlasackiListic.Include(g => g.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
        }

        public IActionResult Odjava(int? id)
        {
            Kandidat k = _context.Kandidat.Include(ka => ka.GlasackiListic).Where(ka => ka.ID == HomeController.currentlyLogged.ID).FirstOrDefault();
            var glasackiListic = _context.GlasackiListic.Include(g => g.Kandidati).FirstOrDefault(g => g.ID == id);
            glasackiListic.Kandidati.Remove(k);
            _context.SaveChanges();
            ViewBag.Message = "Odjavili ste sa izbora!";
            return View("izbori", _context.Izbor.Include(i => i.GlasackiListici).ToList());
        }

        public IActionResult LogOut()
        {
            HomeController.currentlyLogged = null;
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Glasaj(int? id)
        {
            var glasac = _context.Osoba.Include(g => g.HistorijaGlasanja).FirstOrDefault(g => g.ID == HomeController.currentlyLogged.ID);
            var opcije = _context.GlasackiListic.Include(g => g.Kandidati).Include(g => g.Izbor).Where(g => g.ID == id).FirstOrDefault();
            if(DateTime.Now < opcije.Izbor.Pocetak)
            {
                ViewBag.Glasao = "Izbori još nisu počeli!";
                return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());

            }
            if(DateTime.Now > opcije.Izbor.Pocetak.AddHours(12))
            {
                ViewBag.Glasao = "Izbori su završeni!";
                return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
            }
            if (glasac.HistorijaGlasanja == null)
            {
                glasac.HistorijaGlasanja = new HistorijaGlasanja();
                glasac.HistorijaGlasanja.DodajGlas((int)id);
            }
            else
            {
                foreach (var listic in glasac.HistorijaGlasanja.DajGlasove())
                {
                    if (listic == id)
                    {
                        ViewBag.Glasao = "Već ste glasali na ovim izborima";
                        return View("Detalji", _context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
                    }
                }
                glasac.HistorijaGlasanja.DodajGlas((int)id);
            }
            _context.SaveChanges();
            return View(opcije);
        }

        [HttpPost]
        public IActionResult Glasaj(string[] glasovi)
        {
            List<int> lista = new List<int>();
            foreach (string s in glasovi)
            {
                lista.Add(Int32.Parse(s));
            }
            foreach (int id in lista)
            {
                var osoba = _context.Kandidat.FirstOrDefault(k => k.ID == id);
                osoba.brojGlasova++;
            }
            var izbor = _context.Izbor.Include(i => i.Statistika).Where(i => i.ID == currentIzbor).FirstOrDefault();
            var glas = _context.GlasackiListic.Where(i => i.IzborId == currentIzbor).FirstOrDefault();
            if (izbor.Statistika == null) izbor.Statistika = new Statistika();
            if (HomeController.currentlyLogged.Spol == Spol.Muski) izbor.Statistika.GlasoviMusko++;
            else izbor.Statistika.GlasoviZensko++;
            if (glasovi.Length == 0 || glasovi.Length > glas.MaxOdabir) izbor.Statistika.GlasoviNevalidni++;
            else
            {
                izbor.Statistika.GlasoviValidni++;
            }
            _context.SaveChanges();
            ViewBag.PorukaGlasanje = "Hvala što ste glasali!";
            return View("Detalji",_context.GlasackiListic.Include(k => k.Kandidati).Where(i => i.IzborId == currentIzbor).ToList());
        }

        public IActionResult Profil()
        {
            var kandidat = _context.Kandidat.Include(k => k.Profil).Where(k => k.ID == HomeController.currentlyLogged.ID).FirstOrDefault();
            if (kandidat.Profil == null) kandidat.Profil = new Profil();
            _context.SaveChanges();
            return View(kandidat.Profil);
        }

        [HttpPost]
        public IActionResult Profil(string profil)
        {
            var kandidat = _context.Kandidat.Include(k => k.Profil).Where(k => k.ID == HomeController.currentlyLogged.ID).FirstOrDefault();
            if (kandidat.Profil == null) kandidat.Profil = new Profil();
            kandidat.Profil.Opis = profil;
            _context.SaveChanges();
            return View("Index");
        }

        public IActionResult ProfilKandidata(int? id)
        {
            var kandidat = _context.Kandidat.Include(k => k.Profil).Where(k => k.ID == id).FirstOrDefault();
            if (kandidat.Profil == null)
            {
                ViewBag.Message = "Ovaj kandidat nema profil kojeg možete pogledati";
                return View("DetaljiKandidata", _context.Kandidat.Where(k => k.GlasackiListicId == listicId).ToList());
            }
            return View(kandidat.Profil);
        }

        public IActionResult Izvjestaj(int id)
        {
            var izbor = _context.Izbor.Include(i => i.Statistika).Where(i => i.ID == id).FirstOrDefault();
            return View(izbor.Statistika);
        }

    }
}

E-lections/E-lections/Views/Kandidat/Detalji.cshtml
@model IEnumerable<E_lections.Models.GlasackiListic>

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}


<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                Broj kandidata
            </th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @item.Kandidati.Count()
            <td>
                <a asp-action="DetaljiKandidata" asp-route-id="@item.ID">Detalji</a>
            </td>
            <td>
                <a asp-action="Glasaj" asp-controller="Kandidat" asp-area="" asp-route-id="@item.ID">Glasaj</a>
            </td>
            <td>
                <a asp-action="Rezultati" asp-controller="Kandidat" asp-area="" asp-route-id="@item.ID">Rezultati</a>
            </td>
            <td>
                <a asp-action="Prijava" asp-route-id="@item.ID" asp-controller="Kandidat">Prijavite se</a>
            </td>
            @if (ViewBag.Listic != null && ViewBag.Listic == item.ID)
            {
                <td>
                    <a asp-action="Odjava" asp-route-id="@item.ID" asp-controller="Kandidat">Odjavite se</a>
                </td>
            }
        </tr>
        }
    </tbody>
</table>

<div align="center">
    @if (ViewBag.Message != null)
    {
        <h2>@ViewBag.Message</h2>
    }
    @if (ViewBag.PorukaGlasanje != null)
    {
        <h2>
            @ViewBag.PorukaGlasanje
        </h2>
    }
    @if (ViewBag.Glasao != null)
    {
        <h2>@ViewBag.Message</h2>
    }
    </div>

E-lections/E-lections/Views/Kandidat/DetaljiKandidata.cshtml
@model IEnumerable<E_lections.Models.Kandidat>

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}


<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kanton)
            </th>
            <th>
                Stranka
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumRodjenja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Spol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kanton)
                </td>
                @if (item.StrankaId != null)
                {
                    <td>@Html.DisplayFor(modelItem => item.Stranka.Naziv)</td>
                }
                else
                {
                    <td>Nezavisni kandidat</td>
                }
                <td>
                    <a asp-action="ProfilKandidata" asp-route-id="@item.ID">Pogledaj profil</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div align="center">
    @if (ViewBag.Message != null)
    {
        <h2>
            @ViewBag.Message
        </h2>
    }
</div>

E-lections/E-lections/Views/Kandidat/Glasaj.cshtml
@model E_lections.Models.GlasackiListic

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}


@using (Html.BeginForm("Glasaj", "Kandidat"))
{
    <form method="post">
        @foreach (var item in Model.Kandidati)
        {
            @item.Ime @item.Prezime
            <input type="checkbox" name="glasovi" value="@item.ID" />
            <br />
        }
        <input type="submit" value="Glasaj" />
    </form>
}

E-lections/E-lections/Views/Kandidat/Index.cshtml
@model E_lections.Models.Kandidat

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}



    <body>
        <div class="signin">
            <div>
                <ul class="list">
                    <li>
                        <a class="link" asp-action="Stranka" asp-controller="Glasac" asp-area="">Učlani se u stranku</a>
                    </li>
                    <li>
                        <a class="link" asp-action="NapustiStranku" asp-controller="Glasac" asp-area="">Napusti stranku</a>
                    </li>
                </ul>
            </div>
        </div>
        <hr />
        <div align="center">
            @if (ViewBag.Message != null)
            {
                <h2>
                    @ViewBag.Message
                </h2>
            }
        </div>
    </body>

E-lections/E-lections/Views/Kandidat/Izbori.cshtml
@model IEnumerable<E_lections.Models.Izbor>

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}


<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pocetak)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KantonOgranicenje)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pocetak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KantonOgranicenje)
            </td>
            <td>
                <a asp-action="Detalji" asp-route-id="@item.ID">Detaljno</a> |
            </td>
            @if (item.Statistika != null && item.Statistika.Visible == true)
            {
                <a asp-action="Izvjestaj" asp-route-id="@item.ID">Izvještaj</a>
            }
        </tr>
        }
    </tbody>
</table>

E-lections/E-lections/Views/Kandidat/Izvjestaj.cshtml
@model E_lections.Models.Statistika

@{
    ViewData["Title"] = "Izvjestaj";
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}

<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviMusko)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviZensko)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviValidni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlasoviNevalidni)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviMusko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviZensko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviValidni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.GlasoviNevalidni)
            </td>
        </tr>
    </tbody>
</table>

E-lections/E-lections/Views/Kandidat/Profil.cshtml
@model  E_lections.Models.Profil

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}

    <div class="signin">
        @using (Html.BeginForm("Profil", "Kandidat"))
        {
            <form method="post">
                <div>
                 <label>Unesite tekst koji će svi glasači moći vidjeti</label>
                    <div>
                        <textarea class="form-control" name="profil" required="required" cols="20" rows="10">
                @if(Model.Opis != null)
                {
                    @Model.Opis
                }
                </textarea>
                    </div>
                    <div class="btn-group" role="group">
                        <button class="btn" id="btnSignIn" type="submit">Uredi profil</button>
                    </div>
                    <div class="btn-group" role="group"></div>
                </div>
            </form>
        }</div>

E-lections/E-lections/Views/Kandidat/ProfilKandidata.cshtml
@model E_lections.Models.Profil

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}


<div class="signin">
    <textarea rows="10" cols="33" readonly="readonly" >
            @Model.Opis
    </textarea>
</div>

E-lections/E-lections/Views/Kandidat/Rezultati.cshtml
@model IEnumerable<E_lections.Models.Kandidat>

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}

<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brojGlasova)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumRodjenja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Spol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.brojGlasova)
                </td>
            </tr>
        }
    </tbody>
</table>

E-lections/E-lections/Views/Kandidat/Stranka.cshtml
@model IEnumerable<E_lections.Models.Stranka>

@{
    Layout = "~/Views/Shared/_LayoutKandidat.cshtml";
}

<body>
    <table class="content-table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        <a asp-action="UclaniSe" asp-route-id="@item.ID">Učlani se</a> |
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <hr />
    <div align="center">
    @if (ViewBag.Message != null)
    {
        <h2>
            @ViewBag.Message
        </h2>
    }
    </div>
</body>