E-lections/E-lections/Models/Izbor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_lections.Models
{
    public enum StatusIzbora
    {
        [Display(Name = "AKTIVAN")]
        Aktivan,
        [Display(Name = "NEAKTIVAN")]
        Neaktivan
    }

    public class Izbor : IObservable, IIzborPrototip 
    {
        public int ID { get; set; }
        [Required, Display(Name = "Početak")]
        public DateTime Pocetak { get; set; }
        [Required, MaxLength(200), Display(Name = "Opis")]
        public string Opis { get; set; }
        [Required, Display(Name = "Kanton")]
        public string KantonOgranicenje { get; set; }
        [Required, Display(Name = "Status")]
        public StatusIzbora Status { get; set; }

        //veze sa drugim tabelama
        public virtual ICollection<GlasackiListic> GlasackiListici { get; set; }

        public int? StatistikaID { get; set; }
        public virtual Statistika Statistika { get; set; }

        public void Notify()
        {
            //throw new NotImplementedException();
            foreach (GlasackiListic gl in GlasackiListici)
            {
                gl.Update();
            }
        }

        public void Clone()
        {
            throw new NotImplementedException();
        }
    }
}

E-lections/E-lections/Controllers/IzborController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_lections.Models;

namespace E_lections.Controllers
{
    public class IzborController : Controller
    {
        private readonly ELectionsDbContext _context;

        public IzborController(ELectionsDbContext context)
        {
            _context = context;
        }

        // GET: Izbor
        public async Task<IActionResult> Index()
        {
            return View(await _context.Izbor.ToListAsync());
        }

        // GET: Izbor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var izbor = await _context.Izbor.Include(g => g.GlasackiListici)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (izbor == null)
            {
                return NotFound();
            }
            return View(izbor);
        }

        // GET: Izbor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Izbor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Pocetak,Opis,KantonOgranicenje,Status")] Izbor izbor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(izbor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(izbor);
        }

       
        public async Task<IActionResult> Delete(int id)
        {
            var izbor = await _context.Izbor.FindAsync(id);
            _context.Izbor.Remove(izbor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Izvjestaj(int id)
        {
            var izbor = _context.Izbor.Include(i => i.Statistika).Where(i => i.ID == id).FirstOrDefault();
            if (izbor.Statistika == null) izbor.Statistika = new Statistika();
            if (izbor.Pocetak > DateTime.Now) ViewBag.Izvjestaj = "Izbori nisu počeli!";
            else
            {
                ViewBag.Izvjestaj = "Izvještaj je generisan!";
                izbor.Statistika.Visible = true;
                _context.SaveChanges();
            }
            return View("Index", _context.Izbor.Include(g => g.GlasackiListici).ToList());
        }
        
        public IActionResult IzvView(int id)
        {
            var izbor = _context.Izbor.Include(i => i.Statistika).Where(i => i.ID == id).FirstOrDefault();
            if (izbor.Statistika == null) izbor.Statistika = new Statistika();
            return View(izbor.Statistika);
        }

        private bool IzborExists(int id)
        {
            return _context.Izbor.Any(e => e.ID == id);
        }
    }
}

E-lections/E-lections/Views/Izbor/Create.cshtml
@model E_lections.Models.Izbor

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body>
    <div class="signin">
        <div class="col-md-4">
            <form asp-action="Create">
                <div class="form-group">
                    @Html.EditorFor(m => m.Pocetak, new { @type = "date" })
                    <span asp-validation-for="Pocetak" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.TextAreaFor(model => model.Opis, new { @class = "form-control" })
                    <span asp-validation-for="Opis" class="text-danger"></span>
                </div>
                <!--<div class="form-group">
        <span asp-validation-for="KantonOgranicenje" class="text-danger"></span>
        <br />
        <label>
            @Html.RadioButtonFor(model => model.KantonOgranicenje, "SK", new { @class = "radio-button" })
            SK
        </label>
        <label>
            @Html.RadioButtonFor(model => model.KantonOgranicenje, "TK", new { @class = "radio-button" })
            TK
        </label>
        <label>
            @Html.RadioButtonFor(model => model.KantonOgranicenje, "ZDK", new { @class = "radio-button" })
            ZDK
        </label>
    </div>-->

                <div class="form">
                    <select asp-for="@Model.KantonOgranicenje" class="form-control">
                        <option value="Unsko-sanski kanton" class="menuItem">Unsko-sanski kanton</option>
                        <option value="Posavski kanton"class="menuItem">Posavski kanton</option>
                        <option value="Tuzlanski kanton" class="menuItem">Tuzlanski kanton</option>
                        <option value="Zeničko-dobojski kanton" class="menuItem">Zeničko-dobojski kanton</option>
                        <option value="Bosansko-podrinjski kanton Goražde" class="menuItem">Bosansko-podrinjski kanton Goražde</option>
                        <option value="Srednjobosanski kanton" class="menuItem">Srednjobosanski kanton</option>
                        <option value="	Hercegovačko-neretvanski kanton" class="menuItem">	Hercegovačko-neretvanski kanton</option>
                        <option value="Zapadnohercegovački kanton" class="menuItem">Zapadnohercegovački kanton</option>
                        <option value="Kanton Sarajevo" class="menuItem">Kanton Sarajevo</option>
                        <option value="Kanton 10" class="menuItem">Kanton 10</option>
                    </select>
                </div>


                <div class="form">
                    <select asp-for="@Model.Status" class="form-control">
                        <option value="AKTIVAN" class="menuItem">Aktivan</option>
                        <option value="NEAKTIVAN" class="menuItem">Neaktivan</option>
                    </select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Kreiraj" class="btn" />
                </div>
            </form>
        </div>
    </div>

</body>

E-lections/E-lections/Views/Izbor/Details.cshtml
@model E_lections.Models.Izbor

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


    <body>
            <table class="content-table">
                <thead>
                    <tr>
                        <th>
                            Pozicija za koju se glasa
                        </th>
                        <th>
                            Broj opcija
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.GlasackiListici)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Opis)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxOdabir)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
    </body>

E-lections/E-lections/Views/Izbor/Index.cshtml
@model IEnumerable<E_lections.Models.Izbor>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div align="center">
    @using (Html.BeginForm("Create", "Izbor", FormMethod.Get))
    {
        <input type="submit" value="Kreiraj izbore" class="btn" />
    }

    @using (Html.BeginForm("Index", "GlasackiListics", FormMethod.Get))
    {
        <input type="submit" value="Pregled glasačkih listića" class="btn" />
    }
</div>


<table class="content-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pocetak)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Pocetak)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">Detalji</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Obriši</a>
                    <a asp-action="Izvjestaj" asp-route-id="@item.ID">Generiši izvještaj</a>
                    <a asp-action="IzvView" asp-route-id="@item.ID">Pogledaj izvještaj</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div align="center">
    @if (ViewBag.Izvjestaj != null)
    {
        <h2>
            @ViewBag.Izvjestaj
        </h2>
    }
</div>

E-lections/E-lections/Views/Izbor/IzvView.cshtml
@model E_lections.Models.Statistika

@{
    ViewData["Title"] = "IzvView";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



    <table class="content-table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GlasoviMusko)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GlasoviZensko)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GlasoviValidni)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GlasoviNevalidni)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.GlasoviMusko)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.GlasoviZensko)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.GlasoviValidni)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.GlasoviNevalidni)
                    </td>
                </tr>
        </tbody>
    </table>